repository: JonathanDistler/Jonathan-Distler-Portfolio

# Site Settings
locale: "en-US"
title: Jonathan Distler
title_separator: "-"
name: Jonathan Distler
description: Jonathan Distler - Projects and CV
baseurl: "" # For user/organization site, leave this empty
url: "https://jonathandistler.github.io" # Your site URL

# Theme and Style
theme: jekyll-theme-minimal
color_scheme: aqua

sass:
  style: compressed

# Outputting
permalink: /:categories/:title/

collections:
  projects:
    output: true
    permalink: /projects/:name/

# Markdown
markdown: kramdown
kramdown:
  input: GFM

# Plugins
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag